---
#
# Ansible managed
#
repository:
  description: Configure vault_snapshot on Vault.
  homepage: https://robertdebock.nl/
  topics: vaultsnapshot, snapshot, security, ansible, molecule, tox, playbook
